# Generated by Django 5.2.12 on 2026-03-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('staff', models.IntegerField()),
                ('beds_free', models.IntegerField()),
                ('equipment', models.CharField(max_length=200)),
                ('load_percentage', models.IntegerField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('strained', 'Strained'), ('overloaded', 'Overloaded')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('beds', 'Beds'), ('icu', 'ICU Units'), ('ventilator', 'Ventilators'), ('rooms', 'Rooms')], max_length=20)),
                ('total', models.IntegerField()),
                ('available', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('triage_level', models.CharField(choices=[('P1', 'Critical'), ('P2', 'Urgent'), ('P3', 'Standard')], max_length=5)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('treating', 'Being Treated'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WardBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
            ],
        ),
    ]
