# Generated by Django 5.2.12 on 2026-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('beds', 'Beds'), ('icu', 'ICU Units'), ('ventilator', 'Ventilators'), ('rooms', 'Rooms')], max_length=20)),
                ('total', models.IntegerField()),
                ('available', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('staff_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=20)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
