# Generated by Django 5.2.12 on 2026-03-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyresource',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
