# Generated by Django 5.2.12 on 2026-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('triage_level', models.CharField(choices=[('P1', 'Critical'), ('P2', 'Urgent'), ('P3', 'Standard')], max_length=5)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('treating', 'Being Treated'), ('discharged', 'Discharged')], default='waiting', max_length=20)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
