# Generated by Django 5.2.12 on 2026-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_emergencyresource_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('in_use', models.IntegerField()),
                ('available', models.IntegerField()),
                ('maintenance', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'In Use / Active'), ('available', 'Available / Standby'), ('maintenance', 'Under Maintenance')], max_length=20)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
