# Generated by Django 5.2.12 on 2026-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patientqueue'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('staff', models.IntegerField()),
                ('beds_free', models.IntegerField()),
                ('equipment', models.CharField(max_length=200)),
                ('load_percentage', models.IntegerField()),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('strained', 'Strained'), ('overloaded', 'Overloaded')], max_length=20)),
            ],
        ),
    ]
