# Generated by Django 5.2.12 on 2026-03-14 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardbed',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
