# Generated by Django 5.2.12 on 2026-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emergencyresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_name', models.CharField(max_length=100)),
                ('total_beds', models.IntegerField()),
                ('occupied_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
            ],
        ),
    ]
